### ISSUE TITLE
Using AP- cameras with python wrapper gives wrong colors

### ISSUE THREAD

**Issue by JAIJohnny** [JAI-public/pyJds#4]
**Describe the bug**
Using AP-cameras with the Wrapper gives wrong colors. An example is that red is blue as seen below
![image](https://user-images.githubusercontent.com/86404242/211523924-5ef817b8-4cef-47b2-bdf5-3f60c811df7d.png)

Where correct colors can be seen below:
![image](https://user-images.githubusercontent.com/86404242/211524039-de8af5e1-e4f0-4e38-be03-5548c7abc5f3.png)

* pyjds version : 0.0.5
* camera ModelName & DV : AP-1600T-PGE with DV 0.1.0.7

**To Reproduce**
run sample codes of multistream_opencv

**Comment by kodjai** [comment]
When connecting USB camera, this sample could show correct color. I think because pixel format of USB cameras is BGR. It seems OpenCV uses BGR as default, so we could convert RGB format on GigE Vision cameras to BGR with cvtColor() or function of Numpy:
im_rgb = im_bgr[:, :, [2, 1, 0]]
or:
im_rgb = im_bgr[:, :, ::-1]
